"""Add users table

Revision ID: 2cff9b180833
Revises: b137fcd02bd9
Create Date: 2024-11-21 13:29:22.032247

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cff9b180833'
down_revision: str | None = 'b137fcd02bd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saved_group_id', sa.Integer(), nullable=False),
    sa.Column('saved_lecturer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['saved_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['saved_lecturer_id'], ['lecturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
