"""Add technical cards link to groups

Revision ID: 51773d63ecb2
Revises: 6beea1ced756
Create Date: 2024-11-27 21:16:02.138983

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51773d63ecb2'
down_revision: str | None = '6beea1ced756'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('technical_cards_link', sa.String(length=2048), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'technical_cards_link')
    # ### end Alembic commands ###
